use dialog instead of whiptail

diff --git a/ntool b/ntool
--- a/ntool
+++ b/ntool
@@ -26,7 +26,7 @@ MAINPATH="/data/data/com.termux/files/home/.ntool"      #主目录
 RAWURL="https://raw.githubusercontent.com/nnyyaa/ntool/main/"       #GitHub raw地址(我是一只懒懒的猫猫)
 
 if [ "${ARCH}" != "arm64" ];then
-    whiptail --title "ntool-tui:WARNING" --msgbox "未适配的架构:${ARCH} \
+    dialog --title "ntool-tui:WARNING" --msgbox "未适配的架构:${ARCH} \
     通常来说这会造成问题,但是我已竭力适配不同的架构了 \
     你可以测试一下," 0 0
 fi
@@ -35,16 +35,16 @@ cd ${HOME}
 mkdir -p .ntool
 #以下是shitcode之我自己都不认识的function（）
 function wait_for_dev_page(){
-    whiptail --title "ntool-tui:developing page" --msgbox "正在开发" 0 0
+    dialog --title "ntool-tui:developing page" --msgbox "正在开发" 0 0
 }
 
 function bad_empty_input(){
-    whiptail --title "ntool-tui:WARNING" --msgbox "严重错误:不允许的空选项" 0 0 
+    dialog --title "ntool-tui:WARNING" --msgbox "严重错误:不允许的空选项" 0 0 
 }
 
 function backup_page(){      #备份页面function
     clear
-    backup_page_choice=$(whiptail --title "ntool-tui:backup page" --menu "选择一个以继续" 0 0 0 \
+    backup_page_choice=$(dialog --title "ntool-tui:backup page" --menu "选择一个以继续" 0 0 0 \
     "0" "返回脚本主页" \
     "1" "备份termux" \
     "2" "恢复备份" \
@@ -58,7 +58,7 @@ function backup_page(){      #备份页面function
             main_page
             ;;
         1)
-            BACKUP_NAME=$(whiptail --title "ntool-tui:backup name" --inputbox "输入备份名(仅备份$PREFIX以提高速度)" 0 0 3>&1 1>&2 2>&3)
+            BACKUP_NAME=$(dialog --title "ntool-tui:backup name" --inputbox "输入备份名(仅备份$PREFIX以提高速度)" 0 0 3>&1 1>&2 2>&3)
             exitstatus=$?
             if [ $exitstatus = 1 ];then
                 backup_page
@@ -69,7 +69,7 @@ function backup_page(){      #备份页面function
         	cd ~
         	if command -v tar > /dev/null;then
                 if [ -d storage ];then
-                    whiptail --title "ntool-tui:tips" --msgbox "备份可能会很慢,请耐心等待" 0 0
+                    dialog --title "ntool-tui:tips" --msgbox "备份可能会很慢,请耐心等待" 0 0
                     cd /data/data/com.termux/
                     tar -cvpzf ${STORAGEPATH}/${BACKUP_NAME}-tbackup.tgz files
                     echo -e "${GREEN}计算sha1...${RESET}"
@@ -112,12 +112,12 @@ function backup_page(){      #备份页面function
                 tar -xvpzf ${STORAGEPATH}/${RESTORE_NAME} -C /data/data/com.termux/
                 echo -e  "${GREEN}完成，重启生效，按回车以退出${RESET}"
             else
-                whiptail --title "ntool-tui:WARNING" --msgbox "警告:不匹配的sha值!不进行恢复" 0 0
+                dialog --title "ntool-tui:WARNING" --msgbox "警告:不匹配的sha值!不进行恢复" 0 0
                 backup_page 
             fi
             ;;
         3)
-            DEL_BACKUP_NAME=$(whiptail --title "ntool-tui:delete backup" --fselect ${STORAGEPATH}/*-tbackup.tgz 3>&1 1>&2 2>&3)
+            DEL_BACKUP_NAME=$(dialog --title "ntool-tui:delete backup" --fselect ${STORAGEPATH}/*-tbackup.tgz 3>&1 1>&2 2>&3)
             exitstatus=$?
             if [ $exitstatus = 1 ];then
                 backup_page 
@@ -134,7 +134,7 @@ function backup_page(){      #备份页面function
 }
 
 function container_page(){      #容器OS选择
-    CONTAINER_CHOICE=$(whiptail --title "ntool-tui:container installer" --menu "选择一个以继续" 0 0 0 \
+    CONTAINER_CHOICE=$(dialog --title "ntool-tui:container installer" --menu "选择一个以继续" 0 0 0 \
     "1" "Ubuntu 我的存在是因为大家的存在" \
     "2" "Debian 为爱发电,爱的结晶" \
     "3" "卸载/删除" \
@@ -156,12 +156,13 @@ function container_page(){      #容器OS选择
             debian_version_page
             ;;
         3)
-            container_delete
+            container_delete_page
+            ;;
     esac
 }
 
 function debian_version_page(){     #Debian版本选择
-    DEBIAN_VER_CHOICE=$(whiptail --title "ntool-tui:Debian Version" --menu "选择一个以继续 \
+    DEBIAN_VER_CHOICE=$(dialog --title "ntool-tui:Debian Version" --menu "选择一个以继续 \
     同版本不可二次安装，不同版本可以哦" 0 0 0 \
     "1" "Debian10 Buster" \
     "2" "Debian11 Bullseye" \
@@ -184,7 +185,7 @@ function debian_version_page(){     #Debian版本选择
             ;;
     esac
     if [ -d debian-${VERNAME} ];then
-        whiptail --title "ntool-tui:WARNING" --msgbox "不允许的二次安装" 0 0
+        dialog --title "ntool-tui:WARNING" --msgbox "不允许的二次安装" 0 0
         debian_version_page 
         container_install
     fi
@@ -193,7 +194,7 @@ function debian_version_page(){     #Debian版本选择
 
 function ubuntu_version_page(){     #Ubuntu版本选择
     cd ${MAINPATH}
-    UBUNTU_VER_CHOICE=$(whiptail --title "ntool-tui:Ubuntu Version" --menu "选择一个以继续\
+    UBUNTU_VER_CHOICE=$(dialog --title "ntool-tui:Ubuntu Version" --menu "选择一个以继续\
     同版本不可二次安装，不同版本可以哦" 0 0 0 \
     "1" "Ubuntu22.04 Jammy Jellyfish" \
     "2" "Ubuntu20.04 Focal Fossa" \
@@ -216,7 +217,7 @@ function ubuntu_version_page(){     #Ubuntu版本选择
             ;;
     esac
     if [ -d ubuntu-${VERNAME} ];then 
-        whiptail --title "ntool-tui:WARNING" --msgbox "不允许的二次安装" 0 0
+        dialog --title "ntool-tui:WARNING" --msgbox "不允许的二次安装" 0 0
         ubuntu_version_page
     fi
     container_install
@@ -267,11 +268,11 @@ function container_install(){
     groupadd 50123 all_a123
     groupadd 99909997 u999_everybody
     EOF
-    whiptail --title "ntool-tui:success" --msgbox "成功安装${CONTAINER_OS} ${VERCODE} ${VERNAME},输入start${VERNAME}以启动" 0 0
+    dialog --title "ntool-tui:success" --msgbox "成功安装${CONTAINER_OS} ${VERCODE} ${VERNAME},输入start${VERNAME}以启动" 0 0
 }
 
-function container_delete(){
-    DELCONTAINERNAME=$(whiptail --title "ntool-tui:delete container" --inputbox "选择一个
+function container_delete_page(){
+    DELCONTAINERNAME=$(dialog --title "ntool-tui:delete container" --inputbox "选择一个
     `cat .backup.list`" 0 0 3>&1 1>&2 2>&3)
     exitstatus=$?
     if [ -z $DELCONTAINERNAME ];then
@@ -283,7 +284,7 @@ function container_delete(){
         exit 0
     fi 
     rm -rvf ${MAINPATH}/${DELCONTAINERNAME}
-    whiptail --title "ntool-tui:success" --msgbox "删除完成" 0 0
+    dialog --title "ntool-tui:success" --msgbox "删除完成" 0 0
     container_page
 }
 
@@ -321,7 +322,7 @@ echo 'exec $COMMAND' >> ${PREFIX}/bin/start${VERNAME}
 }
 
 function change_source_page(){       #换源
-    SOURCE_CHOICE=$(whiptail --title "ntool-tui:change source" --menu "事实上,你可以使用termux-change-repo来换源,所以这里实际意义不大" 0 0 0 \
+    SOURCE_CHOICE=$(dialog --title "ntool-tui:change source" --menu "事实上,你可以使用termux-change-repo来换源,所以这里实际意义不大" 0 0 0 \
     "1" "使用termux-change-repo(推荐)" \
     "2" "USTC 中国科技大学镜像站" \
     "3" "BFSU 北京外国语大学镜像站" \
@@ -364,13 +365,13 @@ function change_source_page(){       #换源
     sed -i 's@^\(deb.*stable main\)$@#\1\ndeb https://${MIRRORSITE}/termux/apt/termux-main stable main@' $PREFIX/etc/apt/sources.list
     apt update -y
     apt upgrade -y
-    whiptail --title "ntool-tui:change source success" --msgbox  "完成"
+    dialog --title "ntool-tui:change source success" --msgbox  "完成"
     change_source_page
 }
 
 function desktop_page(){
     clear
-    DESKTOP_CHOICE=$(whiptail --title "ntool-tui:desktop install" --menu "选择一个以继续" 0 0 0 \
+    DESKTOP_CHOICE=$(dialog --title "ntool-tui:desktop install" --menu "选择一个以继续" 0 0 0 \
     "1" "安装xfce(较为完整的图形环境)" \
     "2" "仅安装openbox(基础图形环境)" \
     "0" "返回脚本主页面" 3>&1 1>&2 2>&3)
@@ -421,7 +422,7 @@ function desktop_page(){
 }
 
 function other_tool_page(){			#这里是其他功能页的function
-    OTPC=$(whiptail --title "ntool-tui:other tool page" --menu "选择一个以继续" 0 0 0 \
+    OTPC=$(dialog --title "ntool-tui:other tool page" --menu "选择一个以继续" 0 0 0 \
     "1" "网络页面" \
     "2" "工具页面" \
     "3" "换源" \
@@ -448,7 +449,7 @@ function other_tool_page(){			#这里是其他功能页的function
 function ssh_check_install(){
 	clear
 	if command -v ssh;then
-		whiptail --title "ntool-tui:ssh check" --msgbox "ssh功能较少,BUG多多,慎用" 0 0
+		dialog --title "ntool-tui:ssh check" --msgbox "ssh功能较少,BUG多多,慎用" 0 0
 		ssh_page
 	else
 		echo "${RED}未安装ssh客户/服务端${RESET}"
@@ -463,7 +464,7 @@ function ssh_check_install(){
 
 function ssh_page(){
 	clear
-    SSH_CHOICE=$(whiptail --title "ntool-tui:ssh page" --menu "选择一个以继续" 0 0 0 \
+    SSH_CHOICE=$(dialog --title "ntool-tui:ssh page" --menu "选择一个以继续" 0 0 0 \
     "1" "打开sshd服务(让他人连接)" \
     "2" "通过密码连接远程服务器" \
     "3" "生成密钥" \
@@ -507,7 +508,7 @@ function ssh_page(){
 
 function tool_page(){			#这里是其它工具-工具类页面的function
 	clear
-    TPC=$(whiptail --title "ntool-tui:tool page" --menu "选择一个以继续" 0 0 0 \
+    TPC=$(dialog --title "ntool-tui:tool page" --menu "选择一个以继续" 0 0 0 \
     "1" "ping" \
     "2" "ping6" \
     "3" "文件查找" \
@@ -532,10 +533,10 @@ function tool_page(){			#这里是其它工具-工具类页面的function
 
 		1)
 			if command -v ping > /dev/null;then
-                local ip=$(whiptail --title "ntool-tui:ping-ip" --inputbox "输入要进行ping的IP/域名(必填)" 0 0 3>&1 1>&2 2>&3)
-                local time=$(whiptail --title "ntool-tui:ping-time" --inputbox "输入要ping的次数(选填)" 0 0 3>&1 1>&2 2>&3)
-                local speed=$(whiptail --title "ntool-tui:ping-speed" --inputbox "输入ping的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 0 0 3>&1 1>&2 2>&3)
-                local size=$(whiptail --title "ntool-tui:ping-packet-szie" --inputbox "输入ping包大小(选填)(以字节为单位，最大65507)" 0 0 3>&1 1>&2 2>&3)
+                local ip=$(dialog --title "ntool-tui:ping-ip" --inputbox "输入要进行ping的IP/域名(必填)" 0 0 3>&1 1>&2 2>&3)
+                local time=$(dialog --title "ntool-tui:ping-time" --inputbox "输入要ping的次数(选填)" 0 0 3>&1 1>&2 2>&3)
+                local speed=$(dialog --title "ntool-tui:ping-speed" --inputbox "输入ping的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 0 0 3>&1 1>&2 2>&3)
+                local size=$(dialog --title "ntool-tui:ping-packet-szie" --inputbox "输入ping包大小(选填)(以字节为单位，最大65507)" 0 0 3>&1 1>&2 2>&3)
                 if [ -z $ip ] || [ -z $time ] || [ -z $speed ] || [ -z $size ];then
                     bad_empty_input
                     tool_page
@@ -551,10 +552,10 @@ function tool_page(){			#这里是其它工具-工具类页面的function
 			;;
 		2)
 			if command -v ping6 > /dev/null;then
-                local ip=$(whiptail --title "ntool-tui:ping6-ip" --inputbox "输入要进行ping6的IP/域名(必填)" 0 0 3>&1 1>&2 2>&3)
-                local time=$(whiptail --title "ntool-tui:ping6-time" --inputbox "输入要ping6的次数(选填)" 0 0 3>&1 1>&2 2>&3)
-                local speed=$(whiptail --title "ntool-tui:ping6-speed" --inputbox "输入ping6的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 0 0 3>&1 1>&2 2>&3)
-                local size=$(whiptail --title "ntool-tui:ping6-packet-szie" --inputbox "输入ping6包大小(选填)(以字节为单位，最大65507)" 0 0 3>&1 1>&2 2>&3)
+                local ip=$(dialog --title "ntool-tui:ping6-ip" --inputbox "输入要进行ping6的IP/域名(必填)" 0 0 3>&1 1>&2 2>&3)
+                local time=$(dialog --title "ntool-tui:ping6-time" --inputbox "输入要ping6的次数(选填)" 0 0 3>&1 1>&2 2>&3)
+                local speed=$(dialog --title "ntool-tui:ping6-speed" --inputbox "输入ping6的速度(选填)（以秒为单位，省略符号，无root最快0.2）" 0 0 3>&1 1>&2 2>&3)
+                local size=$(dialog --title "ntool-tui:ping6-packet-szie" --inputbox "输入ping6包大小(选填)(以字节为单位，最大65507)" 0 0 3>&1 1>&2 2>&3)
                 if [ -z $ip ] || [ -z $time ] || [ -z $speed ] || [ -z $size ];then
                     bad_empty_input
                     tool_page
@@ -603,17 +604,19 @@ function tool_page(){			#这里是其它工具-工具类页面的function
 
 function check_update(){			#这里是检查/升级的function
     cd ${MAINPATH}
-    wget ${RAWURL}/version -O latest_version > /dev/null 2>&1
-    if [ "`cat latest_version`" != "`cat local_version`" ];then 
-        if (whiptail --title "ntool-tui:update" --yesno "你的版本不是最新版。是否更新？
-        最新版:`cat latest_version`  
-        本地版本:`cat local_version`" 0 0);then 
+    if [ -a local_version ];then
+        echo "ERROR"
+    fi
+    if [ "`cat latest_version`" != "`cat local_version`" ];then
+        if (dialog --title "ntool-tui:update" --yesno "你的版本不是最新版。是否更新？
+            最新版:`cat latest_version`  
+            本地版本:`cat local_version`" 0 0);then 
             bash -c "$(curl https://raw.githubusercontent.com/nnyyaa/ntool/main/install.sh)"
         else
             main_page
         fi
     else
-        whiptail --title "ntool-tui:check update" --msgbox "您的版本为最新版，无需更新" 0 0
+        dialog --title "ntool-tui:check update" --msgbox "您的版本为最新版，无需更新" 0 0
         main_page
     fi 
 }
@@ -621,7 +624,7 @@ function check_update(){			#这里是检查/升级的function
 function web_page(){				#这里是其他功能-网络类页面function
 	clear
 	#echo "这里是最水的页面（doge）"
-    webc=$(whiptail --title "ntool-tui:web page" --menu "选择一个以继续" 0 0 0 \
+    webc=$(dialog --title "ntool-tui:web page" --menu "选择一个以继续" 0 0 0 \
     "1" "安装Nginx" \
     "2" "安装Apache2" \
     "3" "安装php环境" \
@@ -657,7 +660,7 @@ function web_page(){				#这里是其他功能-网络类页面function
 function main_page(){
     clear
     cd ${MAINPATH}
-    mainchoice=$(whiptail --title "ntool-tui:main page" --menu "你的安卓版本为:`getprop ro.build.version.release` \
+    mainchoice=$(dialog --title "ntool-tui:main page" --menu "你的安卓版本为:`getprop ro.build.version.release` \
     `curl https://v1.hitokoto.cn/?encode=text 2>/dev/null` \
     选择一个以继续" 0 0 0  \
     "1" "已烂尾的容器功能" \
@@ -691,7 +694,7 @@ function main_page(){
             backup_page 
             ;;
         4)
-            local BC=$(whiptail --title "ntool-tui:bc PI" --inputbox "输入计算位数    越往后面算的越慢" 0 0 3>&1 1>&2 2>&3)
+            local BC=$(dialog --title "ntool-tui:bc PI" --inputbox "输入计算位数    越往后面算的越慢" 0 0 3>&1 1>&2 2>&3)
             exitstatus=$?
             if [ $exitstatus = 1 ];then
                 main_page
@@ -701,11 +704,11 @@ function main_page(){
             echo "计算开始时间:`date '+%Y-%m-%d %H:%M:%S'`" >> ~/pi.txt
             echo "scale=${BC}; 4*a(1)" | bc -l -q >> ~/pi.txt
             echo "计算结束时间:`date '+%Y-%m-%d %H:%M:%S'`" >> ~/pi.txt
-            whiptail --title "ntool-tui:success" --msgbox "完成!计算结果可在~/pi.txt看到" 0 0
+            dialog --title "ntool-tui:success" --msgbox "完成!计算结果可在~/pi.txt看到" 0 0
             main_page
             ;;
         5)
-            whiptail --title "ntool-一言" --msgbox "`curl https://v1.hitokoto.cn/?encode=text 2>/dev/null`" 15 60
+            dialog --title "ntool-一言" --msgbox "`curl https://v1.hitokoto.cn/?encode=text 2>/dev/null`" 15 60
             main_page
             ;;
         6)
@@ -713,5 +716,8 @@ function main_page(){
             ;;
     esac
 }
+echo -e "${GREEN}正在获取最新版本号...${RESET}"
+cd ${MAINPATH}
+wget ${RAWURL}/version -O latest_version > /dev/null 2>&1
 main_page
 exit 0
