aaa

diff --git a/ntsource b/ntsource
--- a/ntsource
+++ b/ntsource
@@ -999,9 +999,9 @@ function start(){
             echo -e "${GREEN}-h,--help${RESET} print this help"
             echo -e "${GREEN}-v,--version${RESET} print then ntool's version that you've installed."
             echo -e "${GREEN}-g,--github${RESET} open ntool's github page."
-            echo -e "${GREEN}-u,--update${RESET} update ntool from github"
-            echo -e "${YELLOW}-d,--debug${RESET} enable debug mode(set -x).Log will redirected to ~/log.txt."
-            echo -e "${RED}-s,--strict${RESET} enable ${RED}\"set -e\"${RESET} and it will cause many problems such uncompress failed."
+            echo -e "${GREEN}-u,--update${RESET} update ntool from github."
+            echo -e "${YELLOW}-d,--debug${RESET} enable debug mode(set -x).Logs will be redirected to ~/log.txt."
+            echo -e "${RED}-s,--strict${RESET} enable ${RED}\"set -e\"${RESET} and it will cause many problems such as uncompress failed."
             ;;
         -u|--update)
             echo -e "${GREEN}请稍等,正在拉取最新版本号...${RESET}"
